let str = "My name is pArth\t4222 patel";
// let regex = /a/gi;
// let regex = /[aeiou]/gi;
// let regex = /[aeiou]/gi;
// let regex = /[0-9]/gi;
// let regex = /[4|8]/gi;
// let regex = /\d/gi;
// let regex = /\D/gi;
// let regex = /\s/gi;
// let regex = /\S/gi;
// let regex = /\bpA/gi;
// let regex = /\Bme/gi;
// let regex = /name+/gi;
// let regex = /name*/gi;
// let regex = /\w/gi;
// let regex = /\W/gi;
// let regex = /\d{2}/gi;
// let regex = /\d{1,3}/gi;
// let regex = /\d{1,}/gi;
// let regex = /^m/gi;
// let regex = /l$/gi;
// let regex = /me (?=is)/gi;
let regex = /a(?!m)/gi;
console.log(str.search(regex), str.match(regex));
